sudo cat > /etc/prometheus/prometheus.yml.fixed << 'EOF'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
EOF

sudo cp /etc/prometheus/prometheus.yml.fixed /etc/prometheus/prometheus.yml
sudo systemctl restart prometheus
sudo systemctl status prometheus
